import * as fs from "fs";
import * as path from "path";
import { ValidationResult } from "../types";

export async function generateMarkdownReport(
  results: ValidationResult[],
  filePath: string,
  stoppedEarly: boolean
): Promise<void> {
  // Ensure directory exists
  const dir = path.dirname(filePath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  const invalid = results.filter((r) => r.status === "invalid" || r.status === "error");
  const withErrors = results.filter((r) => r.status === "error");
  const withWarnings = results.filter((r) => r.warnings.length > 0 && r.status === "valid");
  const valid = results.filter((r) => r.status === "valid" && r.warnings.length === 0);

  // Group warnings by message
  const warningsByMessage = new Map<string, string[]>();
  for (const result of results) {
    for (const warning of result.warnings) {
      const key = warning.message;
      if (!warningsByMessage.has(key)) {
        warningsByMessage.set(key, []);
      }
      warningsByMessage.get(key)!.push(result.url.replace("https://meetmeatthefair.com", ""));
    }
  }

  const now = new Date();
  const dateStr = now.toLocaleDateString("en-US", {
    month: "long",
    day: "numeric",
    year: "numeric",
  });

  let report = `# GValidate Report: Google Rich Results Test

**Run Date**: ${dateStr}
**Production URL**: https://meetmeatthefair.com
**Status**: ${stoppedEarly ? "⚠️ STOPPED EARLY (errors found)" : "✅ Complete"}

## Summary

| Metric | Count |
|--------|-------|
| Total URLs Tested | ${results.length} |
| Valid (eligible for rich results) | ${valid.length + withWarnings.length} |
| Invalid (errors blocking rich results) | ${invalid.length} |
| With Warnings | ${withWarnings.length} |
| Test Errors (automation failures) | ${withErrors.length} |

`;

  if (invalid.length > 0) {
    report += `## ❌ Invalid Pages (Action Required)

These pages have errors that may prevent rich results from appearing in Google Search.

`;
    for (const result of invalid) {
      const urlPath = result.url.replace("https://meetmeatthefair.com", "");
      report += `### ${urlPath}\n`;
      report += `- **Type**: ${result.entityType}\n`;
      if (result.googleTestUrl && result.googleTestUrl !== "https://search.google.com/test/rich-results") {
        report += `- **Google Test**: [View Result](${result.googleTestUrl})\n`;
      }
      if (result.errors.length > 0) {
        report += `- **Errors**:\n`;
        for (const error of result.errors) {
          report += `  - ${error.message}${error.schema ? ` (${error.schema})` : ""}\n`;
        }
      }
      if (result.detectedItems.length > 0) {
        report += `- **Detected Items**: ${result.detectedItems.map((i) => i.type).join(", ")}\n`;
      }
      report += "\n";
    }
  }

  if (warningsByMessage.size > 0) {
    report += `## ⚠️ Warnings by Category

These warnings don't block rich results but may improve them if addressed.

`;
    const warningEntries = Array.from(warningsByMessage.entries());
    for (const [message, urls] of warningEntries) {
      report += `### ${message} (${urls.length} pages)\n`;
      // Show first 10 URLs
      const displayUrls = urls.slice(0, 10);
      for (const url of displayUrls) {
        report += `- ${url}\n`;
      }
      if (urls.length > 10) {
        report += `- ... and ${urls.length - 10} more\n`;
      }
      report += "\n";
    }
  }

  if (valid.length > 0) {
    report += `## ✅ Valid Pages

${valid.length} pages passed validation with no errors or warnings.

<details>
<summary>Show valid pages</summary>

`;
    for (const result of valid) {
      const urlPath = result.url.replace("https://meetmeatthefair.com", "");
      const items = result.detectedItems.map((i) => i.type).join(", ") || "N/A";
      report += `- ${urlPath} (${items})\n`;
    }
    report += `\n</details>\n\n`;
  }

  report += `## Recommendations

`;

  if (invalid.length > 0) {
    report += `1. **Priority 1**: Fix ${invalid.length} invalid page(s) - these may NOT be eligible for rich results\n`;
  }

  if (warningsByMessage.size > 0) {
    let priority = invalid.length > 0 ? 2 : 1;
    const recommendationEntries = Array.from(warningsByMessage.entries());
    for (const [message, urls] of recommendationEntries) {
      report += `${priority}. **Priority ${priority}**: ${message} (${urls.length} pages)\n`;
      priority++;
      if (priority > 5) break; // Limit to top 5 recommendations
    }
  }

  if (invalid.length === 0 && warningsByMessage.size === 0) {
    report += "All pages passed validation. No action required. 🎉\n";
  }

  report += `
---

*Report generated by gvalidate using Google's Rich Results Test*
`;

  fs.writeFileSync(filePath, report);
}
