-- OPE-35 (2026-07-01) — promoter-enrichment rails: state model + backfill.
--
-- Adds the per-promoter enrichment lifecycle columns (the promoter analog of
-- the vendor-roster rails) and seeds them for existing rows. The enqueue hook
-- (computePromoterEnrichment in @takemetothefair/constants) is authoritative
-- going forward; this backfill mirrors its logic in SQL as a one-time seed.
--
-- DDL generated by drizzle-kit (db:generate, now usable again post-OPE-21);
-- the backfill below is hand-appended (drizzle never emits data migrations).
ALTER TABLE `promoters` ADD `enrichment_status` text;--> statement-breakpoint
ALTER TABLE `promoters` ADD `enrichment_coverage` text;--> statement-breakpoint
ALTER TABLE `promoters` ADD `last_enriched_at` integer;--> statement-breakpoint
ALTER TABLE `promoters` ADD `enrichment_blocked_reason` text;--> statement-breakpoint

-- Backfill (a): per-field coverage snapshot {hero,logo,description,socials,contact}
-- as JSON booleans, matching computePromoterEnrichment's output shape exactly.
UPDATE promoters SET enrichment_coverage = json_object(
  'hero', json(CASE WHEN hero_image_url IS NOT NULL AND trim(hero_image_url) != '' THEN 'true' ELSE 'false' END),
  'logo', json(CASE WHEN logo_url IS NOT NULL AND trim(logo_url) != '' THEN 'true' ELSE 'false' END),
  'description', json(CASE WHEN description IS NOT NULL AND trim(description) != ''
      AND lower(trim(description)) NOT IN ('event organizer', 'event organizer.')
      AND NOT (lower(description) LIKE '%is an event organizer%' AND length(trim(description)) < 60)
    THEN 'true' ELSE 'false' END),
  'socials', json(CASE WHEN social_links IS NOT NULL AND trim(social_links) NOT IN ('', '[]', '{}')
      AND lower(trim(social_links)) != 'null' THEN 'true' ELSE 'false' END),
  'contact', json(CASE WHEN (contact_email IS NOT NULL AND trim(contact_email) != '')
      OR (contact_phone IS NOT NULL AND trim(contact_phone) != '') THEN 'true' ELSE 'false' END)
);--> statement-breakpoint

-- Backfill (b): derive status from the coverage just written + website presence.
-- all covered -> ENRICHED; no website -> NO_SOURCE; else NEEDS_ENRICHMENT.
-- (No IN_PROGRESS/BLOCKED here — those are agent/operator-owned, never seeded.)
UPDATE promoters SET enrichment_status = CASE
  WHEN json_extract(enrichment_coverage, '$.hero') = 1
   AND json_extract(enrichment_coverage, '$.logo') = 1
   AND json_extract(enrichment_coverage, '$.description') = 1
   AND json_extract(enrichment_coverage, '$.socials') = 1
   AND json_extract(enrichment_coverage, '$.contact') = 1
    THEN 'ENRICHED'
  WHEN website IS NULL OR trim(website) = '' THEN 'NO_SOURCE'
  ELSE 'NEEDS_ENRICHMENT'
END;
