/**
 * OPE-395 — region definitions for the crawlable facet mesh.
 *
 * ── Why regions key on CITY ─────────────────────────────────────────────────
 * Measured against prod for MA + CT upcoming events before choosing:
 *
 *   venue attached  100%   city  100%   lat/lng  97%   zip  76%
 *
 * City is the only geographic field that is complete, and it is the one people
 * actually type — "fairs in the Berkshires", not "fairs in 01201". A ZIP-prefix
 * scheme would have been self-maintaining but silently drops a quarter of the
 * inventory; a lat/lng bounding box is both incomplete and wrong along borders,
 * where New England towns are small and adjacent regions interleave.
 *
 * ── The failure mode is ABSENCE, never a wrong claim ────────────────────────
 * An unmapped town simply does not appear on a region page. It still appears on
 * the state page and on the month and type facets, so nothing is lost from the
 * index — the event is only missing from one of four ways in. That is the right
 * direction to fail: a region page that omits a fair is incomplete, while one
 * that files Pittsfield under Cape Cod is wrong, and wrong is unrecoverable
 * because a reader who is misled once does not come back.
 *
 * Because absence is silent, `facetRegionCoverage()` measures the mapped share
 * of each state's inventory and a unit test fails if it decays. Drift here
 * shows up as a quietly shrinking region page, which nothing else would catch.
 *
 * ── Maintenance ─────────────────────────────────────────────────────────────
 * These lists cover every town currently hosting an upcoming event plus the
 * larger towns in each region that plausibly will. Municipalities essentially
 * never change, so this is a stable list rather than a moving target: adding a
 * town is a one-line edit, and forgetting to costs one region listing, not
 * correctness.
 *
 * Keep any single region under ~70 towns. The region predicate binds one SQL
 * parameter per town and D1 caps a statement at 100 bound parameters (see
 * `feedback_d1_batch_param_limit`), so a runaway list would throw at query time
 * rather than degrade. `facet-registry.test.ts` asserts the ceiling.
 */

export interface RegionDef {
  /** Display label, used in the H1, <title> and nav. */
  label: string;
  /**
   * A short geographic gloss, shown under the H1. Deliberately about WHERE the
   * region is and nothing else — no claim about any event's hours, price or
   * admission, per the same grounding rule as OPE-394.
   */
  blurb: string;
  /** Lowercased town names, matched against `lower(trim(venues.city))`. */
  cities: readonly string[];
}

/**
 * Region maps, keyed by state slug then region slug.
 *
 * MA and CT only — OPE-395 scopes the launch to those two. A state absent from
 * this map simply gets no region facets, so the other four keep exactly the
 * pages they have today.
 */
export const STATE_REGIONS: Record<string, Record<string, RegionDef>> = {
  massachusetts: {
    berkshires: {
      label: "The Berkshires",
      blurb: "Berkshire County, in the far west of the state.",
      cities: [
        "adams",
        "becket",
        "cheshire",
        "clarksburg",
        "dalton",
        "egremont",
        "great barrington",
        "hancock",
        "hinsdale",
        "lanesborough",
        "lee",
        "lenox",
        "monterey",
        "new marlborough",
        "north adams",
        "otis",
        "pittsfield",
        "richmond",
        "sandisfield",
        "savoy",
        "sheffield",
        "stockbridge",
        "tyringham",
        "west stockbridge",
        "williamstown",
        "windsor",
      ],
    },
    "pioneer-valley": {
      label: "The Pioneer Valley",
      blurb: "The Connecticut River valley — Hampden, Hampshire and Franklin counties.",
      cities: [
        "agawam",
        "amherst",
        "ashfield",
        "belchertown",
        "bernardston",
        "blandford",
        "brimfield",
        "buckland",
        "charlemont",
        "chester",
        "chesterfield",
        "chicopee",
        "colrain",
        "conway",
        "cummington",
        "deerfield",
        "easthampton",
        "east longmeadow",
        "erving",
        "granby",
        "granville",
        "greenfield",
        "hadley",
        "hardwick",
        "hatfield",
        "heath",
        "holyoke",
        "huntington",
        "leverett",
        "longmeadow",
        "ludlow",
        "middlefield",
        "monson",
        "montague",
        "northampton",
        "northfield",
        "palmer",
        "pelham",
        "russell",
        "shelburne",
        "shelburne falls",
        "south hadley",
        "southampton",
        "southwick",
        "springfield",
        "sunderland",
        "wales",
        "ware",
        "warwick",
        "wendell",
        "westfield",
        "west springfield",
        "whately",
        "wilbraham",
        "williamsburg",
        "worthington",
      ],
    },
    "central-massachusetts": {
      label: "Central Massachusetts",
      blurb: "Worcester County and the hill towns around it.",
      cities: [
        "athol",
        "auburn",
        "barre",
        "bolton",
        "boylston",
        "brookfield",
        "charlton",
        "clinton",
        "devens",
        "douglas",
        "dudley",
        "fitchburg",
        "gardner",
        "grafton",
        "harvard",
        "holden",
        "hubbardston",
        "lancaster",
        "leicester",
        "leominster",
        "lunenburg",
        "millbury",
        "northborough",
        "northbridge",
        "orange",
        "oxford",
        "paxton",
        "petersham",
        "princeton",
        "royalston",
        "rutland",
        "shrewsbury",
        "southbridge",
        "spencer",
        "sterling",
        "sturbridge",
        "sutton",
        "templeton",
        "uxbridge",
        "webster",
        "westborough",
        "westminster",
        "winchendon",
        "worcester",
      ],
    },
    "greater-boston": {
      label: "Greater Boston",
      blurb: "Boston and the cities and towns immediately around it.",
      cities: [
        "allston",
        "arlington",
        "belmont",
        "boston",
        "braintree",
        "brighton",
        "brookline",
        "cambridge",
        "canton",
        "charlestown",
        "chelsea",
        "dedham",
        "dorchester",
        "east boston",
        "everett",
        "hyde park",
        "jamaica plain",
        "malden",
        "medford",
        "melrose",
        "milton",
        "needham",
        "newton",
        "quincy",
        "randolph",
        "revere",
        "roslindale",
        "roxbury",
        "somerville",
        "south boston",
        "stoneham",
        "waltham",
        "watertown",
        "wellesley",
        "west roxbury",
        "weymouth",
        "winthrop",
      ],
    },
    "north-shore": {
      label: "The North Shore",
      blurb: "The coast and Merrimack Valley north of Boston.",
      cities: [
        "amesbury",
        "andover",
        "beverly",
        "boxford",
        "danvers",
        "essex",
        "georgetown",
        "gloucester",
        "groveland",
        "hamilton",
        "haverhill",
        "ipswich",
        "lawrence",
        "lowell",
        "lynn",
        "lynnfield",
        "manchester-by-the-sea",
        "marblehead",
        "merrimac",
        "methuen",
        "middleton",
        "nahant",
        "newbury",
        "newburyport",
        "north andover",
        "north reading",
        "peabody",
        "reading",
        "rockport",
        "rowley",
        "salem",
        "salisbury",
        "saugus",
        "swampscott",
        "tewksbury",
        "topsfield",
        "wakefield",
        "wenham",
        "west newbury",
        "wilmington",
        "woburn",
      ],
    },
    metrowest: {
      label: "MetroWest",
      blurb: "The suburbs and farm towns west of Boston, along I-495 and Route 2.",
      cities: [
        "acton",
        "ashland",
        "ayer",
        "bedford",
        "bellingham",
        "billerica",
        "boxborough",
        "burlington",
        "carlisle",
        "chelmsford",
        "concord",
        "dover",
        "dracut",
        "framingham",
        "franklin",
        "groton",
        "holliston",
        "hopkinton",
        "hudson",
        "lexington",
        "lincoln",
        "littleton",
        "marlborough",
        "maynard",
        "medfield",
        "medway",
        "millis",
        "milford",
        "natick",
        "norfolk",
        "pepperell",
        "sherborn",
        "shirley",
        "southborough",
        "stow",
        "sudbury",
        "townsend",
        "tyngsborough",
        "wayland",
        "westford",
        "weston",
        "wrentham",
      ],
    },
    "south-shore": {
      label: "The South Shore",
      blurb: "The coast and towns south of Boston, from Quincy to Plymouth.",
      cities: [
        "abington",
        "avon",
        "bridgewater",
        "brockton",
        "carver",
        "cohasset",
        "duxbury",
        "east bridgewater",
        "easton",
        "foxborough",
        "halifax",
        "hanover",
        "hanson",
        "hingham",
        "holbrook",
        "hull",
        "kingston",
        "lakeville",
        "marshfield",
        "mansfield",
        "middleborough",
        "north easton",
        "norton",
        "norwell",
        "pembroke",
        "plymouth",
        "plympton",
        "rockland",
        "scituate",
        "sharon",
        "stoughton",
        "wareham",
        "west bridgewater",
        "whitman",
      ],
    },
    "cape-cod-and-the-islands": {
      label: "Cape Cod & the Islands",
      blurb: "Barnstable County plus Martha's Vineyard and Nantucket.",
      cities: [
        "barnstable",
        "bourne",
        "brewster",
        "chatham",
        "chilmark",
        "cotuit",
        "dennis",
        "dennis port",
        "eastham",
        "edgartown",
        "falmouth",
        "harwich",
        "hyannis",
        "mashpee",
        "nantucket",
        "oak bluffs",
        "orleans",
        "osterville",
        "provincetown",
        "sandwich",
        "south yarmouth",
        "truro",
        "vineyard haven",
        "wellfleet",
        "west tisbury",
        "woods hole",
        "yarmouth",
      ],
    },
    "south-coast": {
      label: "The South Coast",
      blurb: "Bristol County and the Buzzards Bay shore.",
      cities: [
        "acushnet",
        "attleboro",
        "berkley",
        "dartmouth",
        "dighton",
        "fairhaven",
        "fall river",
        "freetown",
        "marion",
        "mattapoisett",
        "new bedford",
        "north attleborough",
        "raynham",
        "rehoboth",
        "seekonk",
        "somerset",
        "swansea",
        "taunton",
        "westport",
      ],
    },
  },

  connecticut: {
    "litchfield-hills": {
      label: "The Litchfield Hills",
      blurb: "The northwest corner — Litchfield County's hill towns and lakes.",
      cities: [
        "barkhamsted",
        "bethlehem",
        "bridgewater",
        "canaan",
        "colebrook",
        "cornwall",
        "goshen",
        "harwinton",
        "kent",
        "litchfield",
        "morris",
        "new hartford",
        "new milford",
        "norfolk",
        "north canaan",
        "plymouth",
        "riverton",
        "roxbury",
        "salisbury",
        "sharon",
        "terryville",
        "thomaston",
        "torrington",
        "warren",
        "washington",
        "watertown",
        "winchester center",
        "winsted",
        "woodbury",
      ],
    },
    "greater-hartford": {
      label: "Greater Hartford",
      blurb: "The capital region and the towns along the river north of it.",
      cities: [
        "avon",
        "berlin",
        "bloomfield",
        "bristol",
        "burlington",
        "canton",
        "east granby",
        "east hartford",
        "east windsor",
        "enfield",
        "farmington",
        "glastonbury",
        "granby",
        "hartford",
        "manchester",
        "marlborough",
        "newington",
        "new britain",
        "plainville",
        "plantsville",
        "rocky hill",
        "simsbury",
        "somers",
        "south windsor",
        "southington",
        "suffield",
        "vernon",
        "west hartford",
        "west simsbury",
        "wethersfield",
        "windsor",
        "windsor locks",
      ],
    },
    "new-haven-area": {
      label: "The New Haven Area",
      blurb: "South-central Connecticut and the shoreline towns either side of it.",
      cities: [
        "ansonia",
        "bethany",
        "branford",
        "cheshire",
        "derby",
        "east haven",
        "guilford",
        "hamden",
        "madison",
        "meriden",
        "milford",
        "new haven",
        "north branford",
        "north haven",
        "orange",
        "wallingford",
        "west haven",
        "woodbridge",
      ],
    },
    "fairfield-county": {
      label: "Fairfield County",
      blurb: "The southwest corner, from Greenwich up to Danbury.",
      cities: [
        "bethel",
        "bridgeport",
        "brookfield",
        "danbury",
        "darien",
        "easton",
        "fairfield",
        "greenwich",
        "monroe",
        "new canaan",
        "newtown",
        "norwalk",
        "redding",
        "ridgefield",
        "shelton",
        "sherman",
        "stamford",
        "stratford",
        "trumbull",
        "weston",
        "westport",
        "wilton",
      ],
    },
    "connecticut-river-valley": {
      label: "The Connecticut River Valley",
      blurb: "Middlesex County — the lower river and the shoreline around Old Saybrook.",
      cities: [
        "chester",
        "clinton",
        "cromwell",
        "deep river",
        "durham",
        "east haddam",
        "east hampton",
        "essex",
        "haddam",
        "killingworth",
        "middlefield",
        "middletown",
        "old lyme",
        "old saybrook",
        "portland",
        "westbrook",
      ],
    },
    "mystic-country": {
      label: "Mystic Country",
      blurb: "Southeastern Connecticut — New London County and the coast.",
      cities: [
        "colchester",
        "east lyme",
        "franklin",
        "gales ferry",
        "groton",
        "lebanon",
        "ledyard",
        "lisbon",
        "lyme",
        "montville",
        "mystic",
        "new london",
        "north stonington",
        "norwich",
        "preston",
        "salem",
        "sprague",
        "stonington",
        "uncasville",
        "waterford",
      ],
    },
    "quiet-corner": {
      label: "The Quiet Corner",
      blurb: "The rural northeast — Windham and Tolland counties.",
      cities: [
        "andover",
        "ashford",
        "bolton",
        "brooklyn",
        "canterbury",
        "chaplin",
        "columbia",
        "coventry",
        "eastford",
        "ellington",
        "hampton",
        "hebron",
        "killingly",
        "mansfield",
        "plainfield",
        "pomfret",
        "putnam",
        "scotland",
        "south woodstock",
        "stafford springs",
        "sterling",
        "storrs",
        "thompson",
        "tolland",
        "union",
        "willimantic",
        "willington",
        "woodstock",
      ],
    },
    "naugatuck-valley": {
      label: "The Naugatuck Valley",
      blurb: "The valley towns between Waterbury and the shoreline.",
      cities: [
        "beacon falls",
        "middlebury",
        "naugatuck",
        "oxford",
        "prospect",
        "seymour",
        "southbury",
        "waterbury",
        "wolcott",
      ],
    },
  },
};

/** Region slugs defined for a state, in declaration order. */
export function regionSlugsFor(stateSlug: string): string[] {
  return Object.keys(STATE_REGIONS[stateSlug] ?? {});
}

/** One region definition, or null when the state or slug is unknown. */
export function findRegion(stateSlug: string, regionSlug: string): RegionDef | null {
  return STATE_REGIONS[stateSlug]?.[regionSlug] ?? null;
}
