import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Providers } from "@/components/layout/providers";
import { Header } from "@/components/layout/header";
import { Footer } from "@/components/layout/footer";
import { UnverifiedBanner } from "@/components/layout/unverified-banner";
import { WebVitals } from "@/components/WebVitals";
import { ErrorAnalyticsBridge } from "@/components/ErrorAnalyticsBridge";
import { OrganizationSchema } from "@/components/seo/OrganizationSchema";

/**
 * Fonts are SELF-HOSTED, not fetched from Google at build time.
 *
 * `next/font/google` downloads the font files during `next build`. That makes
 * every production build depend on fonts.googleapis.com being reachable from
 * the CI runner, and when it is not the build fails outright — it broke three
 * builds in a single day (#863, #867, #870) with `nextFontError`, each costing a
 * full rebuild. A font is a static asset that changes maybe once a year; making
 * it a build-time network call trades a permanent fragility for nothing.
 *
 * These are the same files Google serves, downloaded once and committed:
 * the latin-subset VARIABLE woff2 for each family, which is what
 * `subsets: ["latin"]` was already requesting. One variable file covers the
 * whole weight range, so it replaces the four static Fraunces instances the
 * previous config pulled (400/500/600/700) and is smaller than their sum.
 *
 * `adjustFontFallback` is set explicitly because `next/font/google` was doing
 * it for us: it derives size-adjust metrics for a fallback face so text does
 * not reflow when the webfont swaps in. Dropping it would have quietly
 * regressed CLS on every page — the kind of side effect that does not show up
 * in a build log.
 *
 * Both families are SIL OFL 1.1; see `src/app/fonts/OFL.txt`.
 */
const fraunces = localFont({
  src: "./fonts/fraunces-latin-var.woff2",
  variable: "--font-display",
  display: "swap",
  weight: "400 700",
  style: "normal",
  adjustFontFallback: "Times New Roman",
  fallback: ["Georgia", "Cambria", "Times New Roman", "serif"],
});

const inter = localFont({
  src: "./fonts/inter-latin-var.woff2",
  variable: "--font-sans",
  display: "swap",
  weight: "100 900",
  style: "normal",
  adjustFontFallback: "Arial",
  fallback: [
    "system-ui",
    "-apple-system",
    "Segoe UI",
    "Roboto",
    "Helvetica Neue",
    "Arial",
    "sans-serif",
  ],
});

export const metadata: Metadata = {
  title: "Meet Me at the Fair - Discover Local Fairs & Events",
  description:
    "Find fairs, festivals, and community events in your area. Connect with vendors and promoters.",
  metadataBase: new URL("https://meetmeatthefair.com"),
  openGraph: {
    title: "Meet Me at the Fair",
    description:
      "Find fairs, festivals, and community events in your area. Connect with vendors and promoters.",
    url: "https://meetmeatthefair.com",
    siteName: "Meet Me at the Fair",
    type: "website",
    locale: "en_US",
    images: [
      {
        url: "https://meetmeatthefair.com/og-default.png",
        width: 1200,
        height: 630,
        alt: "Meet Me at the Fair — Discover Local Fairs, Festivals & Events",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Meet Me at the Fair",
    description:
      "Find fairs, festivals, and community events in your area. Connect with vendors and promoters.",
    images: ["https://meetmeatthefair.com/og-default.png"],
  },
  manifest: "/manifest.json",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // Design System keystone PR 4 (2026-06-07):
    //   - `suppressHydrationWarning` is REQUIRED by next-themes — their
    //     pre-hydration <script> mutates className before React renders,
    //     which would otherwise emit a "Warning: Prop className did not
    //     match" hydration error. Per next-themes docs.
    //   - Dropped hardcoded `bg-cream` from the className. The page bg
    //     is now driven by the `:root { --background }` CSS var (defined
    //     in globals.css PR 1) which the body styles consume. Keeping
    //     `bg-cream` here would override the .dark theme on <html>.
    <html lang="en" className={`${fraunces.variable} ${inter.variable}`} suppressHydrationWarning>
      <head>
        {/*
          esbuild `keepNames` helper polyfill — MUST be the first thing the
          browser executes, hence top of <head> (runs before any <body>
          script).

          Why this exists: the OpenNext/Cloudflare Workers build bundles the
          server with esbuild's `keepNames: true`, which rewrites named
          functions to add a `__name(fn, "fn")` call that preserves
          Function.prototype.name. next-themes' no-flash theme script is
          generated by stringifying a function (`fn.toString()`) and injecting
          it inline via dangerouslySetInnerHTML — so the bundled `__name(...)`
          call gets baked into the emitted inline script. That script runs in
          the BROWSER, where esbuild's `__name` banner (worker-scope only)
          doesn't exist → `ReferenceError: __name is not defined` on every
          page load (next-themes#370). This was latent on Pages/next-on-pages
          and surfaced at the 2026-06-10 OpenNext cutover.

          Defining a global `__name` (classic-script scope → window) satisfies
          the bare reference. Faithful to esbuild's impl (sets .name, returns
          the target) and idempotent. Defends any future bundled-then-inlined
          script too. Cleaner long-term fix would be disabling keepNames in the
          OpenNext esbuild pass, but that knob isn't cleanly exposed today.
        */}
        <script
          dangerouslySetInnerHTML={{
            __html: `window.__name||(window.__name=function(t,n){try{Object.defineProperty(t,"name",{value:n,configurable:true})}catch(e){}return t});`,
          }}
        />
        <link rel="preconnect" href="https://www.googletagmanager.com" />
        <link rel="preconnect" href="https://challenges.cloudflare.com" />
        <link rel="dns-prefetch" href="https://www.google-analytics.com" />
      </head>
      <body className="antialiased min-h-screen flex flex-col">
        <OrganizationSchema />
        <Providers>
          <WebVitals />
          <ErrorAnalyticsBridge />
          <Header />
          <UnverifiedBanner />
          <main id="main-content" className="flex-1">
            {children}
          </main>
          <Footer />
        </Providers>
        {/*
        GA4 install — plain <script> elements, NOT next/script's <Script>.
        Next.js App Router puts <Script strategy="afterInteractive"> content
        into the RSC payload (escaped string) and injects it client-side,
        which means: (a) the loader src never appears as a literal <script>
        tag in SSR HTML, (b) the inline init renders only as escaped JSON,
        not executable JavaScript. Same problem as @next/third-parties's
        <GoogleAnalytics> — see PR #107 / #108 for the iteration.
        Plain <script> in JSX renders directly to SSR HTML (same pattern
        the CF Insights beacon below has used since day one). `async` lets
        the browser parse the rest of the document while gtag.js loads.

        IMPORTANT — script placement: these <script> tags must live INSIDE
        <body>. Previously placed as direct children of <html> (between
        </body> and </html>), they caused a site-wide React #418 hydration
        error: SSR emitted them at end-of-document while React 19's client
        reconciler clustered inline scripts near OrganizationSchema's
        JSON-LD at the top of <body>. The position mismatch then triggered
        secondary "Cannot read properties of null (reading 'parentNode')"
        TypeErrors as React's recovery code tried to swap orphaned
        streaming markers. Root-caused via playwright browser repro
        2026-05-18 (SSR-vs-hydrated DOM diff at byte 893). Keep these
        inside <body>.

        XSS-safety: the inline init's content is built from
        process.env.NEXT_PUBLIC_GA_ID, a build-time env var sourced from a
        GitHub Actions secret. It is NOT user-controllable runtime input —
        no sanitizer needed. The G- value is also a public, low-entropy
        identifier (it ships to every browser anyway).
      */}
        {process.env.NEXT_PUBLIC_GA_ID && (
          <>
            {/* OPE-578 — `crossOrigin` is what de-blinds this script's errors.
                OPE-105 added it to our own bundles, but those are served
                SAME-ORIGIN from /_next/static, where the browser already hands
                `window.onerror` the real message and stack. The attribute is
                belt-and-braces there and does nothing for `Script error.`.
                These two third-party tags are the only CROSS-origin scripts on
                the page, so they are the only ones that can produce it.
                Verified 2026-08-28: this host answers
                `access-control-allow-origin: https://meetmeatthefair.com`, so
                an anonymous CORS load succeeds and the errors become
                attributable. See the guard test for the precondition. */}
            <script
              async
              crossOrigin="anonymous"
              src={`https://www.googletagmanager.com/gtag/js?id=${process.env.NEXT_PUBLIC_GA_ID}`}
            />
            <script
              dangerouslySetInnerHTML={{
                __html: `window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
if (!window.__ga4Inited) {
  window.__ga4Inited = true;
  gtag('js', new Date());
  gtag('config', '${process.env.NEXT_PUBLIC_GA_ID}');
}`,
              }}
            />
          </>
        )}
        {process.env.NEXT_PUBLIC_CF_BEACON_TOKEN && (
          // OPE-578 — see the note on the gtag tag above. Verified 2026-08-28:
          // this host answers `access-control-allow-origin: *`.
          <script
            defer
            crossOrigin="anonymous"
            src="https://static.cloudflareinsights.com/beacon.min.js"
            data-cf-beacon={`{"token": "${process.env.NEXT_PUBLIC_CF_BEACON_TOKEN}"}`}
          />
        )}
      </body>
    </html>
  );
}
