/**
 * Tests for vtnhfairs.org scraper.
 *
 * Multi-state scraper (Vermont + New Hampshire fairs association). The page
 * is generated by Wix and the scraper does positional analysis on differently-
 * styled spans to associate fair names with their date / contact / website.
 * Brittle to Wix template changes — these tests pin behavior so a regression
 * in the regexes shows up immediately rather than producing silently-empty
 * scrape results.
 */

import { describe, it, expect, vi, beforeEach, afterEach } from "vitest";
import {
  scrapeVtFairs,
  scrapeNhFairs,
  scrapeVtNhFairs,
  scrapeVtNhEventDetails,
} from "../vtnhfairs";

const mockFetch = vi.fn();
global.fetch = mockFetch;

beforeEach(() => {
  vi.clearAllMocks();
});

afterEach(() => {
  vi.restoreAllMocks();
});

/**
 * Build a minimal Wix-style HTML fixture for one or more fairs.
 * Each fair contributes: a font-size:20px name span, a color_15 date span,
 * and (optionally) a "Visit Website" link.
 */
function buildHtml(opts: {
  year: number;
  fairs: Array<{
    name: string;
    date: string;
    website?: string;
    contact?: string;
  }>;
}): string {
  let html = `<html><body>`;
  html += `<span class="wixui-rich-text__text">${opts.year} Fairs</span>`;
  for (const fair of opts.fairs) {
    html += `<span style="font-size: 20px;" class="wixui-rich-text__text">${fair.name}</span>`;
    html += `<span class="color_15 wixui-rich-text__text">${fair.date}</span>`;
    if (fair.contact) {
      html += `<span style="font-size: 16px;" class="wixui-rich-text__text">Contact: ${fair.contact}</span>`;
    }
    if (fair.website) {
      html += `<a href="${fair.website}">Visit Website</a>`;
    }
  }
  html += `</body></html>`;
  return html;
}

describe("scrapeVtFairs", () => {
  it("returns error on non-OK HTTP response", async () => {
    mockFetch.mockResolvedValueOnce({
      ok: false,
      status: 503,
      statusText: "Service Unavailable",
    });

    const result = await scrapeVtFairs();

    expect(result.success).toBe(false);
    expect(result.events).toEqual([]);
    expect(result.error).toContain("503");
  });

  it("returns error on network failure", async () => {
    mockFetch.mockRejectedValueOnce(new Error("Connection refused"));

    const result = await scrapeVtFairs();

    expect(result.success).toBe(false);
    expect(result.error).toBe("Connection refused");
  });

  it("hits the Vermont-specific URL", async () => {
    mockFetch.mockResolvedValueOnce({
      ok: true,
      text: () => Promise.resolve(buildHtml({ year: 2026, fairs: [] })),
    });

    await scrapeVtFairs();

    expect(mockFetch).toHaveBeenCalledOnce();
    expect(String(mockFetch.mock.calls[0][0])).toBe("https://www.vtnhfairs.org/copy-of-fairs");
  });

  it("parses fairs with same-month date ranges (e.g. 'July 24-26')", async () => {
    const html = buildHtml({
      year: 2026,
      fairs: [
        {
          name: "Champlain Valley Fair",
          date: "July 24-26",
          website: "https://champlainvalleyfair.org",
        },
      ],
    });
    mockFetch.mockResolvedValueOnce({ ok: true, text: () => Promise.resolve(html) });

    const result = await scrapeVtFairs();

    expect(result.success).toBe(true);
    expect(result.events).toHaveLength(1);
    const event = result.events[0];
    expect(event.name).toBe("Champlain Valley Fair");
    expect(event.startDate?.getMonth()).toBe(6); // July
    expect(event.startDate?.getDate()).toBe(24);
    expect(event.endDate?.getDate()).toBe(26);
    expect(event.datesConfirmed).toBe(true);
    expect(event.website).toBe("https://champlainvalleyfair.org");
    expect(event.ticketUrl).toBe("https://champlainvalleyfair.org");
    expect(event.state).toBe("VT");
    expect(event.sourceName).toBe("vtnhfairs.org-vt");
  });

  it("parses cross-month date ranges (e.g. 'July 29 - August 2')", async () => {
    const html = buildHtml({
      year: 2026,
      fairs: [{ name: "Tunbridge World's Fair", date: "July 29 - August 2" }],
    });
    mockFetch.mockResolvedValueOnce({ ok: true, text: () => Promise.resolve(html) });

    const result = await scrapeVtFairs();

    expect(result.events[0].startDate?.getMonth()).toBe(6); // July
    expect(result.events[0].startDate?.getDate()).toBe(29);
    expect(result.events[0].endDate?.getMonth()).toBe(7); // August
    expect(result.events[0].endDate?.getDate()).toBe(2);
  });

  it("strips ordinal suffixes ('25th', '27th') from dates", async () => {
    const html = buildHtml({
      year: 2026,
      fairs: [{ name: "Addison County Fair", date: "August 25th-27th" }],
    });
    mockFetch.mockResolvedValueOnce({ ok: true, text: () => Promise.resolve(html) });

    const result = await scrapeVtFairs();

    expect(result.events[0].startDate?.getDate()).toBe(25);
    expect(result.events[0].endDate?.getDate()).toBe(27);
    expect(result.events[0].datesConfirmed).toBe(true);
  });

  it("parses single-day events", async () => {
    const html = buildHtml({
      year: 2026,
      fairs: [{ name: "One Day Fair", date: "September 12" }],
    });
    mockFetch.mockResolvedValueOnce({ ok: true, text: () => Promise.resolve(html) });

    const result = await scrapeVtFairs();

    expect(result.events[0].startDate?.getMonth()).toBe(8); // September
    expect(result.events[0].startDate?.getDate()).toBe(12);
    expect(result.events[0].endDate?.getDate()).toBe(12);
  });

  it("flags datesConfirmed=false for 'TBD' / 'To be determined' dates", async () => {
    const html = buildHtml({
      year: 2026,
      fairs: [{ name: "Mystery Fair", date: "To be determined" }],
    });
    mockFetch.mockResolvedValueOnce({ ok: true, text: () => Promise.resolve(html) });

    const result = await scrapeVtFairs();

    expect(result.events).toHaveLength(1);
    expect(result.events[0].datesConfirmed).toBe(false);
    expect(result.events[0].startDate).toBeUndefined();
    expect(result.events[0].endDate).toBeUndefined();
  });

  it("flags datesConfirmed=false for 'No fair this year'", async () => {
    const html = buildHtml({
      year: 2026,
      fairs: [{ name: "Cancelled Fair", date: "No fair this year" }],
    });
    mockFetch.mockResolvedValueOnce({ ok: true, text: () => Promise.resolve(html) });

    const result = await scrapeVtFairs();

    expect(result.events[0].datesConfirmed).toBe(false);
  });

  it("uses the year from the page header rather than the current year", async () => {
    const html = buildHtml({
      year: 2027,
      fairs: [{ name: "Future Fair", date: "June 6-8" }],
    });
    mockFetch.mockResolvedValueOnce({ ok: true, text: () => Promise.resolve(html) });

    const result = await scrapeVtFairs();

    expect(result.events[0].startDate?.getFullYear()).toBe(2027);
  });

  it("decodes HTML entities in fair names", async () => {
    const html = buildHtml({
      year: 2026,
      fairs: [{ name: "Smith &amp; Jones Family Fair", date: "July 4" }],
    });
    mockFetch.mockResolvedValueOnce({ ok: true, text: () => Promise.resolve(html) });

    const result = await scrapeVtFairs();

    expect(result.events[0].name).toBe("Smith & Jones Family Fair");
  });

  it("does not stash contact info in description (would pollute SEO meta)", async () => {
    // Pre-fix behavior: contact text was written into description as
    // `Contact: Jane Doe (802) 555-1234`. That polluted meta descriptions
    // on imported events and caused the recommendations rule for missing
    // descriptions to silently pass them. Description is now left undefined
    // so the meta-description fallback chain takes over downstream.
    const html = buildHtml({
      year: 2026,
      fairs: [
        {
          name: "Contact Fair",
          date: "August 1-3",
          contact: "Jane Doe (802) 555-1234",
        },
      ],
    });
    mockFetch.mockResolvedValueOnce({ ok: true, text: () => Promise.resolve(html) });

    const result = await scrapeVtFairs();

    expect(result.events[0].description).toBeUndefined();
  });

  it("parses multiple fairs from a single page in correct order", async () => {
    const html = buildHtml({
      year: 2026,
      fairs: [
        { name: "First Fair", date: "May 1-3" },
        { name: "Second Fair", date: "June 10-12" },
        { name: "Third Fair", date: "July 20-22" },
      ],
    });
    mockFetch.mockResolvedValueOnce({ ok: true, text: () => Promise.resolve(html) });

    const result = await scrapeVtFairs();

    expect(result.events).toHaveLength(3);
    expect(result.events.map((e) => e.name)).toEqual(["First Fair", "Second Fair", "Third Fair"]);
  });

  it("returns empty events array when page contains no fair-styled spans", async () => {
    mockFetch.mockResolvedValueOnce({
      ok: true,
      text: () => Promise.resolve("<html><body>No fairs here</body></html>"),
    });

    const result = await scrapeVtFairs();

    expect(result.success).toBe(true);
    expect(result.events).toEqual([]);
  });

  it("does NOT return the year-header span as a fair", async () => {
    // Year header has no font-size:20px style, but in case a future page
    // change picks it up by accident, the parser explicitly filters
    // "YYYY Fairs" name patterns.
    const html = `
      <html><body>
      <span style="font-size: 20px;" class="wixui-rich-text__text">2026 Fairs</span>
      <span class="color_15 wixui-rich-text__text">May 1-3</span>
      <span style="font-size: 20px;" class="wixui-rich-text__text">Real Fair</span>
      <span class="color_15 wixui-rich-text__text">June 10-12</span>
      </body></html>
    `;
    mockFetch.mockResolvedValueOnce({ ok: true, text: () => Promise.resolve(html) });

    const result = await scrapeVtFairs();

    expect(result.events.map((e) => e.name)).not.toContain("2026 Fairs");
    expect(result.events.map((e) => e.name)).toContain("Real Fair");
  });

  it("populates a venue object with the fair name (parens stripped) and state", async () => {
    const html = buildHtml({
      year: 2026,
      fairs: [{ name: "Big Fair (since 1880)", date: "August 1-3" }],
    });
    mockFetch.mockResolvedValueOnce({ ok: true, text: () => Promise.resolve(html) });

    const result = await scrapeVtFairs();

    expect(result.events[0].venue?.name).toBe("Big Fair");
    expect(result.events[0].venue?.state).toBe("VT");
  });
});

describe("scrapeNhFairs", () => {
  it("hits the New-Hampshire-specific URL", async () => {
    mockFetch.mockResolvedValueOnce({
      ok: true,
      text: () => Promise.resolve(buildHtml({ year: 2026, fairs: [] })),
    });

    await scrapeNhFairs();

    expect(String(mockFetch.mock.calls[0][0])).toBe("https://www.vtnhfairs.org/copy-of-fairs-1");
  });

  it("tags scraped events with state=NH and sourceName=vtnhfairs.org-nh", async () => {
    const html = buildHtml({
      year: 2026,
      fairs: [{ name: "Hopkinton State Fair", date: "September 3-7" }],
    });
    mockFetch.mockResolvedValueOnce({ ok: true, text: () => Promise.resolve(html) });

    const result = await scrapeNhFairs();

    expect(result.events[0].state).toBe("NH");
    expect(result.events[0].sourceName).toBe("vtnhfairs.org-nh");
  });
});

describe("scrapeVtNhFairs (legacy alias)", () => {
  it("delegates to scrapeVtFairs", async () => {
    mockFetch.mockResolvedValueOnce({
      ok: true,
      text: () => Promise.resolve(buildHtml({ year: 2026, fairs: [] })),
    });

    await scrapeVtNhFairs();

    expect(String(mockFetch.mock.calls[0][0])).toBe("https://www.vtnhfairs.org/copy-of-fairs");
  });
});

describe("scrapeVtNhEventDetails", () => {
  it("returns empty object — details are baked into initial scrape, never overwrite", async () => {
    // This is intentional. The top-level scrape already captures the venue
    // website (which is the legitimate ticket URL); a follow-up "details"
    // fetch would just hit the listing page again and clobber that with the
    // aggregator URL. Returning {} short-circuits the details flow.
    const result = await scrapeVtNhEventDetails("https://www.vtnhfairs.org/copy-of-fairs");

    expect(result).toEqual({});
    expect(mockFetch).not.toHaveBeenCalled();
  });
});
