/**
 * OPE-1154 — a page we could not read is not a source.
 *
 * Specimen: event b52c6acf, 2026-09-22. The registration link returned
 * CloudFront's 403 page; six citations were still written against that URL
 * with the 403 as their excerpt (so `source_verifiable` derived TRUE), while
 * the values came from the email body.
 */
import { describe, it, expect, beforeEach, vi } from "vitest";
import { createTestDb, type TestDb } from "./setup-db.js";
import { recordSourceCitations } from "../src/email-handlers/pipeline-citations.js";
import { eventDataCitations, events, promoters } from "../src/schema.js";
import { eq } from "drizzle-orm";

let db: TestDb;

beforeEach(() => {
  ({ db } = createTestDb());
  vi.spyOn(console, "warn").mockImplementation(() => {});
  db.insert(promoters)
    .values({ id: "promoter-1", companyName: "Test Promoter", slug: "test-promoter" })
    .run();
  db.insert(events)
    .values({
      id: "event-1",
      name: "VCS Holiday Market",
      slug: "vcs-holiday-market",
      promoterId: "promoter-1",
      status: "PENDING",
    })
    .run();
});

const URL_ = "https://holiday-market-vendor-registration-49978.cheddarup.com/";
const extracted = {
  url: URL_,
  event: {
    name: "VCS Holiday Market",
    startDate: "2026-12-05",
    endDate: "2026-12-05",
    startTime: "07:00",
    estimatedAttendance: 50,
    applicationDeadline: "2026-09-24",
  },
};
const rows = () =>
  db.select().from(eventDataCitations).where(eq(eventDataCitations.eventId, "event-1")).all();

describe("OPE-1154 — no citation from a blocked page", () => {
  it("writes nothing when the snapshot is CloudFront's 403", async () => {
    const res = await recordSourceCitations(db, {
      eventId: "event-1",
      extracted,
      source: { kind: "url", url: URL_ },
      fromAddress: "organizer@example.org",
      snapshot: {
        title: "ERROR: The request could not be satisfied",
        text: "403 ERROR The request could not be satisfied. Request blocked. Generated by cloudfront (CloudFront)",
        fetchedAt: new Date("2026-09-22T22:32:52Z"),
      },
    });
    expect(res).toEqual({ inserted: 0, reason: "blocked-page" });
    expect(rows()).toHaveLength(0);
  });

  it("landmark: the same extraction from a REAL page is cited", async () => {
    const res = await recordSourceCitations(db, {
      eventId: "event-1",
      extracted,
      source: { kind: "url", url: URL_ },
      fromAddress: "organizer@example.org",
      snapshot: {
        title: "VCS Holiday Market — Vendor Registration",
        text: "Saturday, December 5, 2026. Doors open 9 AM.",
        fetchedAt: new Date("2026-09-22T22:32:52Z"),
      },
    });
    expect(res.inserted).toBeGreaterThan(0);
    expect(rows().length).toBe(res.inserted);
  });

  it("the email body is still cited as the email", async () => {
    const res = await recordSourceCitations(db, {
      eventId: "event-1",
      extracted: { ...extracted, url: "" },
      source: { kind: "body" },
      fromAddress: "organizer@example.org",
    });
    expect(res.inserted).toBeGreaterThan(0);
    expect(new Set(rows().map((r) => r.sourceUrl))).toEqual(
      new Set(["email://organizer@example.org"])
    );
  });
});

describe("OPE-1154 rework — a map/search URL is never cited, whatever it returned", () => {
  const MAPS = "https://www.google.com/maps/search/153+Hospital+Street%C2%A0+Augusta,+ME";

  it("SPECIMEN: Google's consent wall on a Maps search writes nothing (0e39e183)", async () => {
    const res = await recordSourceCitations(db, {
      eventId: "event-1",
      extracted: { ...extracted, url: MAPS },
      source: { kind: "url", url: MAPS },
      fromAddress: "organizer@example.org",
      snapshot: {
        title: "Before you continue to Google Maps",
        text: "Before you continue to Google Maps We use cookies and data to deliver and maintain Google services",
        fetchedAt: new Date("2026-10-04T00:42:00Z"),
      },
    });
    expect(res).toEqual({ inserted: 0, reason: "non-source-url" });
    expect(rows()).toHaveLength(0);
  });

  it("with NO snapshot at all (the 08-29 Gilford shape) it still writes nothing", async () => {
    const res = await recordSourceCitations(db, {
      eventId: "event-1",
      extracted: { ...extracted, url: MAPS },
      source: { kind: "url", url: MAPS },
      fromAddress: "organizer@example.org",
    });
    expect(res).toEqual({ inserted: 0, reason: "non-source-url" });
    expect(rows()).toHaveLength(0);
  });

  it("control: the same extraction from the organizer's ticket page is cited", async () => {
    const TICKETS = "https://events.humanitix.com/lilac-festival-planning-meeting";
    const res = await recordSourceCitations(db, {
      eventId: "event-1",
      extracted: { ...extracted, url: TICKETS },
      source: { kind: "url", url: TICKETS },
      fromAddress: "organizer@example.org",
      snapshot: {
        title: "Lilac Festival Planning Meeting | Humanitix",
        text: "October 15, 2026 · 153 Hospital Street, Augusta",
        fetchedAt: new Date("2026-10-04T00:42:00Z"),
      },
    });
    expect(res.inserted).toBeGreaterThan(0);
  });
});
