/**
 * OPE-1154 — origin DENY pages are not content.
 *
 * Both specimens came back through Browser Rendering as `success: true` and
 * were stored as citation evidence: CloudFront's 403 on a cheddarup.com
 * registration link (2026-09-22) and an "Access Denied" page behind a
 * share.google link (2026-09-24).
 */
import { describe, it, expect, vi, afterEach } from "vitest";
import { detectChallengePage, detectBlockedSnapshot } from "./challenge-page";
import { fetchViaBrowserRendering } from "./browser-rendering";

// The CloudFront page, as served (trimmed).
const CLOUDFRONT_403 = `<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>403 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
Request blocked.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: abc123==
</PRE>
</BODY></HTML>`;

const ACCESS_DENIED = `<html><head><title>Access Denied</title></head><body><h1>Access Denied</h1>
You don't have permission to access this resource. Reference #18.5e3f2217.1727200000.1a2b3c</body></html>`;

const NGINX_403 = `<html><head><title>403 Forbidden</title></head><body><center><h1>403 Forbidden</h1></center><hr><center>nginx</center></body></html>`;

describe("OPE-1154 — deny pages classify as blocked", () => {
  it.each([
    ["cloudfront", CLOUDFRONT_403],
    ["access-denied", ACCESS_DENIED],
    ["http-403", NGINX_403],
  ])("%s", (vendor, html) => {
    const v = detectChallengePage(html, null);
    expect(v.isChallenge).toBe(true);
    expect(v.vendor).toBe(vendor);
  });

  it("does NOT flag ordinary pages that merely use the words", () => {
    // Positive landmark for the negative assertions: real prose, both phrases.
    const faq = `<html><head><title>Fryeburg Fair — FAQ</title></head><body>
      <p>Access denied to pets in the exhibition halls. Requests blocked by the gate
      staff can be appealed at the office. A 403 Forbidden sign is on the barn.</p></body></html>`;
    expect(detectChallengePage(faq, null).isChallenge).toBe(false);
  });
});

describe("OPE-1154 — the same verdict from a stored TITLE + TEXT snapshot", () => {
  it("classifies the specimens as they were captured on the citation rows", () => {
    // Captured on event b52c6acf's citations, 2026-09-22.
    expect(
      detectBlockedSnapshot(
        "ERROR: The request could not be satisfied",
        "403 ERROR The request could not be satisfied. Request blocked. Generated by cloudfront (CloudFront)"
      ).isChallenge
    ).toBe(true);
    // Captured on event b5ac5b32's citations, 2026-09-24 (title only).
    expect(detectBlockedSnapshot("Access Denied", "").isChallenge).toBe(true);
  });

  it("passes a real page", () => {
    expect(
      detectBlockedSnapshot("Maine Cheese Festival", "Sunday, September 13, 2026 — Manson Park")
        .isChallenge
    ).toBe(false);
  });
});

describe("OPE-1154 — Browser Rendering returning a deny page is a FAILED fetch", () => {
  const realFetch = global.fetch;
  afterEach(() => {
    global.fetch = realFetch;
  });

  it("reports ok:false for the CloudFront page, so the route never returns success", async () => {
    global.fetch = vi.fn(
      async () =>
        new Response(JSON.stringify({ success: true, result: CLOUDFRONT_403 }), {
          status: 200,
          headers: { "content-type": "application/json" },
        })
    ) as unknown as typeof fetch;
    const out = await fetchViaBrowserRendering(
      "https://holiday-market-vendor-registration-49978.cheddarup.com/",
      { CLOUDFLARE_ACCOUNT_ID: "a", CLOUDFLARE_BROWSER_RENDERING_TOKEN: "t" }
    );
    expect(out.ok).toBe(false);
    if (out.ok) throw new Error("unreachable");
    expect(out.error).toContain("cloudfront");
  });
});
