/**
 * OPE-949 — the env-type drift check compares binding NAMES and KINDS, so the
 * two shapes wrangler emits for one binding (entry module resolvable or not)
 * compare equal, and a real binding change does not.
 */
import { describe, it, expect } from "vitest";
import { compareBindings, parseEnvBindings } from "../../../scripts/check-env-types-drift";

// Wrangler's raw output when it CAN resolve the entry module (tab indent).
const RESOLVABLE = `/* eslint-disable */
// Generated by Wrangler (hash: aaaa)
interface __BaseEnv_WorkerEnv {
\tDB: D1Database;
\tBURST_COUNTER: DurableObjectNamespace<import("./src/index").BurstCounter>;
\tINBOUND_EMAIL: Workflow<
\t\tParameters<import("./src/index").InboundEmailWorkflow["run"]>[0]["payload"]
\t>;
\tSELF: Service<typeof import("./src/index").default>;
\tDEPLOY_ENV: "production";
\tEMAIL_JOBS: Queue;
\tFEATURE_FLAGS: {
\t\tphotos: boolean;
\t};
}
declare namespace Cloudflare {
\tinterface Env extends __BaseEnv_WorkerEnv {}
}`;

// The same config, entry module NOT resolvable, prettier-formatted (2 spaces).
const UNRESOLVABLE = `// Generated by Wrangler (hash: bbbb)
interface __BaseEnv_WorkerEnv {
  DB: D1Database;
  BURST_COUNTER: DurableObjectNamespace /* BurstCounter */;
  INBOUND_EMAIL: Workflow /* InboundEmailWorkflow */;
  SELF: Fetcher /* meetmeatthefair-mcp */;
  DEPLOY_ENV: string;
  EMAIL_JOBS: Queue;
  FEATURE_FLAGS: {
    photos: boolean;
  };
}`;

describe("OPE-949 — parseEnvBindings", () => {
  it("both shapes wrangler emits for one config parse to the same binding map", () => {
    const a = parseEnvBindings(RESOLVABLE, "WorkerEnv");
    const b = parseEnvBindings(UNRESOLVABLE, "WorkerEnv");
    // Landmark: the multi-line Workflow<…> argument and the JSON var's nested
    // member are not bindings.
    expect(a.size).toBe(7);
    expect(Object.fromEntries(a)).toEqual({
      DB: "D1Database",
      BURST_COUNTER: "DurableObjectNamespace",
      INBOUND_EMAIL: "Workflow",
      SELF: "Fetcher",
      DEPLOY_ENV: "string",
      EMAIL_JOBS: "Queue",
      FEATURE_FLAGS: "object",
    });
    expect(compareBindings(a, b)).toEqual({ missing: [], stale: [], retyped: [] });
  });

  it("throws rather than returning an empty map when the interface is absent", () => {
    expect(() => parseEnvBindings(RESOLVABLE, "CloudflareEnv")).toThrow(/not found/);
  });

  it("parses the committed files for real (non-empty, DB present)", async () => {
    const { readFileSync } = await import("node:fs");
    for (const [f, i] of [
      ["cloudflare-env.d.ts", "CloudflareEnv"],
      ["mcp-server/worker-env.d.ts", "WorkerEnv"],
    ] as const) {
      const m = parseEnvBindings(readFileSync(f, "utf8"), i);
      expect(m.size).toBeGreaterThan(10);
      expect(m.get("DB")).toBe("D1Database");
    }
  });
});

describe("OPE-949 — compareBindings reports each kind of drift", () => {
  const committed = parseEnvBindings(UNRESOLVABLE, "WorkerEnv");

  it("a binding added to the config without regenerating is MISSING", () => {
    const config = new Map(committed).set("NEXT_CACHE_DO_QUEUE", "DurableObjectNamespace");
    expect(compareBindings(committed, config).missing).toEqual(["NEXT_CACHE_DO_QUEUE"]);
  });

  it("a binding removed from the config is STALE", () => {
    const config = new Map(committed);
    config.delete("EMAIL_JOBS");
    expect(compareBindings(committed, config).stale).toEqual(["EMAIL_JOBS"]);
  });

  it("a binding whose kind changed is RETYPED", () => {
    const config = new Map(committed).set("EMAIL_JOBS", "KVNamespace");
    expect(compareBindings(committed, config).retyped).toEqual([
      { name: "EMAIL_JOBS", committed: "Queue", config: "KVNamespace" },
    ]);
  });
});
